[workspace]
members = [ "crates/*" ]

[workspace.package]
version = "2.0.0"
description = "zip reading and writing"
repository = "https://github.com/fasterthanlime/rc-zip"
license = "Apache-2.0 OR MIT"
authors = ["Amos Wenger <amoswenger@gmail.com>"]

[workspace.dependencies]
positioned-io = { version = "0.3.1" }

[profile.release]
debug = 1
