[package]
name = "rc-zip"
version = "1.0.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"
description = "zip reading and writing"
repository = "https://github.com/fasterthanlime/rc-zip"
readme = "README.md"
license = "Apache-2.0 OR MIT"

keywords = ["zip", "unzip"]
categories = ["compression"]

[badges]
travis-ci = { repository = "fasterthanlime/rc-zip" }
maintenance = { status = "experimental" }

[profile.dev]
opt-level = 0
debug = true

[profile.release]
debug = true

[dependencies]
nom = "5.0.0"
pretty-hex = "0.3.0"
circular = "0.3.0"
chrono = "0.4.24"
chardet = "0.2.4"
encoding_rs = "0.8.32"
crc32fast = "1.2.0"
positioned-io = { version = "0.2.2", optional = true }
libflate = { version = "0.1.25", optional = true }
tracing = "0.1.37"
oem_cp = "2.0.0"

[features]
default = ["sync"]
sync = ["positioned-io", "libflate"]

[workspace]
members = [ ".", "samples/jean" ]
default-members = [ ".", "samples/jean" ]

