[package]
name = "jean"
version.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
edition = "2018"

[dependencies]
rc-zip = { path = "../rc-zip" }
clap = "2.33.0"
humansize = "1.1.0"
positioned-io.workspace = true
indicatif = "0.11.0"
