[package]
name = "rc-zip"
version.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
edition = "2021"
description = "zip reading and writing"
readme = "../../README.md"

keywords = ["zip", "unzip"]
categories = ["compression"]

[dependencies]
nom = "7.1.3"
pretty-hex = "0.3.0"
circular = "0.3.0"
chrono = "0.4.24"
chardet = "0.2.4"
encoding_rs = "0.8.32"
crc32fast = "1.3.2"
positioned-io = { workspace = true, optional = true }
libflate = { version = "1.3.0", optional = true }
tracing = "0.1.37"
oem_cp = "2.0.0"
thiserror = "1.0.40"
chardetng = "0.1.17"

[features]
default = ["sync", "file"]
sync = ["positioned-io", "libflate"]
file = []
