[package]
name = "jean"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[dependencies]
rc-zip = { path = "../.." }
clap = "2.33.0"
humansize = "1.1.0"
positioned-io = "0.2.2"
indicatif = "0.11.0"
