name: test

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install Rust specified toolchain
        run: rustup show
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: just,nextest,cargo-llvm-cov
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features
      - name: Run tests and collect coverage
        run: just ci-test
      - name: Upload coverage information
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
  test-windows:
    runs-on: windows-2022
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install Rust specified toolchain
        run: rustup show
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --all-features
      - name: Run cargo nextest
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --profile ci